using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.Text;
using System.Net;
using System.Net.Http;

namespace Hestia.backend
{
    /*
     * Note that the network handler in hestia android extends from application and uses serializable.
     * I have made sure that the package required for this is in the config, Application is something else though.
     */
    class NetworkHandler : ISerializable
    {
        private string ip { get; set; }
        private int port { get; set; }

        //Empty constructor for compiling.
        public NetworkHandler (string ip, int port)
        {
            this.ip = ip;
            this.port = port;
        }

        public void get(string endpoint)
        {
            //dummy code http code for now.
            using (var client = new HttpClient(new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate }))
            {
                client.BaseAddress = new Uri(endpoint);
                HttpResponseMessage response = client.GetAsync("answers?order=desc&sort=activity&site=stackoverflow").Result;
                response.EnsureSuccessStatusCode();
                string result = response.Content.ReadAsStringAsync().Result;
                Console.WriteLine("Result: " + result);
            }
        }

        public void post()
        {

        }

        public void delete()
        {

        } 

        public void put()
        {

        }

        // Stub generated by serializable interface
        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            throw new NotImplementedException();
        }
    }
}
