//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hestia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hestia.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activatorcell.
        /// </summary>
        public static string activatorCell {
            get {
                return ResourceManager.GetString("activatorCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activators/.
        /// </summary>
        public static string activatorsPath {
            get {
                return ResourceManager.GetString("activatorsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servercelladddevice.
        /// </summary>
        public static string addDeviceChooseServerCell {
            get {
                return ResourceManager.GetString("addDeviceChooseServerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDeviceChooseServer.
        /// </summary>
        public static string AddDeviceChooseServerViewController {
            get {
                return ResourceManager.GetString("AddDeviceChooseServerViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDeviceIcon.
        /// </summary>
        public static string addDeviceIcon {
            get {
                return ResourceManager.GetString("addDeviceIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Add device.
        /// </summary>
        public static string addDeviceTitle {
            get {
                return ResourceManager.GetString("addDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddManufacturer.
        /// </summary>
        public static string AddManufacturerViewController {
            get {
                return ResourceManager.GetString("AddManufacturerViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hest.io.
        /// </summary>
        public static string apiURL {
            get {
                return ResourceManager.GetString("apiURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hestia.
        /// </summary>
        public static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth0ViewController.
        /// </summary>
        public static string auth0ViewController {
            get {
                return ResourceManager.GetString("auth0ViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete!.
        /// </summary>
        public static string autocomplete {
            get {
                return ResourceManager.GetString("autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change credentials.
        /// </summary>
        public static string changeCredsTitle {
            get {
                return ResourceManager.GetString("changeCredsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change IP.
        /// </summary>
        public static string changeIpTitle {
            get {
                return ResourceManager.GetString("changeIpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string changeNameTitle {
            get {
                return ResourceManager.GetString("changeNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _1wsVGXJbkEm8kwcueB5seyxm37E1rWl.
        /// </summary>
        public static string clientId {
            get {
                return ResourceManager.GetString("clientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string defaultNumberOfSections {
            get {
                return ResourceManager.GetString("defaultNumberOfSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string defaultNumberOfServers {
            get {
                return ResourceManager.GetString("defaultNumberOfServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8000.
        /// </summary>
        public static string defaultPort {
            get {
                return ResourceManager.GetString("defaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://.
        /// </summary>
        public static string defaultPrefix {
            get {
                return ResourceManager.GetString("defaultPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessTokenHestia.
        /// </summary>
        public static string defaultsAccessTokenHestia {
            get {
                return ResourceManager.GetString("defaultsAccessTokenHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipHestia.
        /// </summary>
        public static string defaultsIpHestia {
            get {
                return ResourceManager.GetString("defaultsIpHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localHestia.
        /// </summary>
        public static string defaultsLocalHestia {
            get {
                return ResourceManager.GetString("defaultsLocalHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordHestia.
        /// </summary>
        public static string defaultsPasswordHestia {
            get {
                return ResourceManager.GetString("defaultsPasswordHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portHestia.
        /// </summary>
        public static string defaultsPortHestia {
            get {
                return ResourceManager.GetString("defaultsPortHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servernameHestia.
        /// </summary>
        public static string defaultsServerNameHestia {
            get {
                return ResourceManager.GetString("defaultsServerNameHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usernameHestia.
        /// </summary>
        public static string defaultsUsernameHestia {
            get {
                return ResourceManager.GetString("defaultsUsernameHestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices/.
        /// </summary>
        public static string devicePath {
            get {
                return ResourceManager.GetString("devicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices2.
        /// </summary>
        public static string devices2StoryBoard {
            get {
                return ResourceManager.GetString("devices2StoryBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tableCell.
        /// </summary>
        public static string devicesMainCell {
            get {
                return ResourceManager.GetString("devicesMainCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tableCellDeviceType.
        /// </summary>
        public static string deviceTypeCell {
            get {
                return ResourceManager.GetString("deviceTypeCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hestio.eu.auth0.com.
        /// </summary>
        public static string domainAuth0 {
            get {
                return ResourceManager.GetString("domainAuth0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find server.
        /// </summary>
        public static string findServerTitle {
            get {
                return ResourceManager.GetString("findServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalSettingsScreen.
        /// </summary>
        public static string GlobalSettingsScreen {
            get {
                return ResourceManager.GetString("GlobalSettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string hashCodeMultiplier {
            get {
                return ResourceManager.GetString("hashCodeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESTIA.IP.
        /// </summary>
        public static string hestiaIp {
            get {
                return ResourceManager.GetString("hestiaIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fathomless-reef-69954.herokuapp.com.
        /// </summary>
        public static string hestiaWebServerAddress {
            get {
                return ResourceManager.GetString("hestiaWebServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string initialCount {
            get {
                return ResourceManager.GetString("initialCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94.212.164.28.
        /// </summary>
        public static string ipDaan {
            get {
                return ResourceManager.GetString("ipDaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP_OF_SERVER.
        /// </summary>
        public static string ipOfServer {
            get {
                return ResourceManager.GetString("ipOfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localGlobalViewController.
        /// </summary>
        public static string localGlobalViewController {
            get {
                return ResourceManager.GetString("localGlobalViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalSettingsScreen.
        /// </summary>
        public static string LocalSettingsScreen {
            get {
                return ResourceManager.GetString("LocalSettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loginToConnect.
        /// </summary>
        public static string loginToConnectSegue {
            get {
                return ResourceManager.GetString("loginToConnectSegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string mainStoryBoard {
            get {
                return ResourceManager.GetString("mainStoryBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainToAuth0.
        /// </summary>
        public static string mainToAuth0 {
            get {
                return ResourceManager.GetString("mainToAuth0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainToDevicesMain.
        /// </summary>
        public static string mainToDevicesMain {
            get {
                return ResourceManager.GetString("mainToDevicesMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainToServerConnect.
        /// </summary>
        public static string mainToServerConnect {
            get {
                return ResourceManager.GetString("mainToServerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tableCellManufacturer.
        /// </summary>
        public static string manufacturerCell {
            get {
                return ResourceManager.GetString("manufacturerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigationDevicesMain.
        /// </summary>
        public static string navigationControllerDevicesMain {
            get {
                return ResourceManager.GetString("navigationControllerDevicesMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigationServerList.
        /// </summary>
        public static string navigationControllerServerSelectList {
            get {
                return ResourceManager.GetString("navigationControllerServerSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device.
        /// </summary>
        public static string newDeviceName {
            get {
                return ResourceManager.GetString("newDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device found.
        /// </summary>
        public static string noDeviceFound {
            get {
                return ResourceManager.GetString("noDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        public static string pluginPathFront {
            get {
                return ResourceManager.GetString("pluginPathFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins/.
        /// </summary>
        public static string pluginsPath {
            get {
                return ResourceManager.GetString("pluginsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        public static string pluginsPathMid {
            get {
                return ResourceManager.GetString("pluginsPathMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you have pronounced the device name correctly..
        /// </summary>
        public static string pronounceDeviceNameCorrectly {
            get {
                return ResourceManager.GetString("pronounceDeviceNameCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tableCellProperty.
        /// </summary>
        public static string propertyCell {
            get {
                return ResourceManager.GetString("propertyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request.
        /// </summary>
        public static string requestPath {
            get {
                return ResourceManager.GetString("requestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string requestTimeout {
            get {
                return ResourceManager.GetString("requestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localGlobalToServerSelect.
        /// </summary>
        public static string segueToLocalGlobalToServerSelect {
            get {
                return ResourceManager.GetString("segueToLocalGlobalToServerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverDiscoverySegue.
        /// </summary>
        public static string segueToServerDiscovery {
            get {
                return ResourceManager.GetString("segueToServerDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select servers.
        /// </summary>
        public static string selectServerTitle {
            get {
                return ResourceManager.GetString("selectServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servercell.
        /// </summary>
        public static string serverCell {
            get {
                return ResourceManager.GetString("serverCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerToDevices.
        /// </summary>
        public static string serverConnectToDevicesSegue {
            get {
                return ResourceManager.GetString("serverConnectToDevicesSegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Found:.
        /// </summary>
        public static string serverFound {
            get {
                return ResourceManager.GetString("serverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server.
        /// </summary>
        public static string serverNotFound {
            get {
                return ResourceManager.GetString("serverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servers/.
        /// </summary>
        public static string serversPath {
            get {
                return ResourceManager.GetString("serversPath", resourceCulture);
            }
        }
        
        public static string usersPath {
            get {
                return ResourceManager.GetString("usersPath", resourceCulture);
            }
        }
        
        public static string hestiaWebServerAddress {
            get {
                return ResourceManager.GetString("hestiaWebServerAddress", resourceCulture);
            }
        }
        
        public static string segueToServerDiscovery {
            get {
                return ResourceManager.GetString("segueToServerDiscovery", resourceCulture);
            }
        }
        
        public static string localGlobalViewController {
            get {
                return ResourceManager.GetString("localGlobalViewController", resourceCulture);
            }
        }
        
        public static string segueToLocalGlobalToServerSelect {
            get {
                return ResourceManager.GetString("segueToLocalGlobalToServerSelect", resourceCulture);
            }
        }
        
        public static string selectServerTitle {
            get {
                return ResourceManager.GetString("selectServerTitle", resourceCulture);
            }
        }
        
        public static string addDeviceIcon {
            get {
                return ResourceManager.GetString("addDeviceIcon", resourceCulture);
            }
        }
        
        public static string voiceControlIcon {
            get {
                return ResourceManager.GetString("voiceControlIcon", resourceCulture);
            }
        }
        
        public static string LocalSettingsScreen {
            get {
                return ResourceManager.GetString("LocalSettingsScreen", resourceCulture);
            }
        }
        
        public static string GlobalSettingsScreen {

        /// <summary>
        ///   Looks up a localized string similar to HestiaClient.
        /// </summary>
        public static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _hestia._tcp..
        /// </summary>
        public static string serviceType {
            get {
                return ResourceManager.GetString("serviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ip here.
        /// </summary>
        public static string setIpHint {
            get {
                return ResourceManager.GetString("setIpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to speech recognition denied.
        /// </summary>
        public static string speechAccessDenied {
            get {
                return ResourceManager.GetString("speechAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow access to speech recognition in settings..
        /// </summary>
        public static string speechAllowAccess {
            get {
                return ResourceManager.GetString("speechAllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during speech recognition.
        /// </summary>
        public static string speechError {
            get {
                return ResourceManager.GetString("speechError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a command..
        /// </summary>
        public static string speechNotACommand {
            get {
                return ResourceManager.GetString("speechNotACommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while recording..
        /// </summary>
        public static string speechRecordError {
            get {
                return ResourceManager.GetString("speechRecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t start recording, something went wrong.
        /// </summary>
        public static string speechStartRecordProblem {
            get {
                return ResourceManager.GetString("speechStartRecordProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string toggleRank {
            get {
                return ResourceManager.GetString("toggleRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        public static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/.
        /// </summary>
        public static string usersPath {
            get {
                return ResourceManager.GetString("usersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android version too low.
        /// </summary>
        public static string versionTooLow {
            get {
                return ResourceManager.GetString("versionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDevice.
        /// </summary>
        public static string viewControllerAddDevice {
            get {
                return ResourceManager.GetString("viewControllerAddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDeviceProperties.
        /// </summary>
        public static string viewControllerAddDeviceProperties {
            get {
                return ResourceManager.GetString("viewControllerAddDeviceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceControlIcon.
        /// </summary>
        public static string voiceControlIcon {
            get {
                return ResourceManager.GetString("voiceControlIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceControlIcon2.
        /// </summary>
        public static string voiceControlIconInverted {
            get {
                return ResourceManager.GetString("voiceControlIconInverted", resourceCulture);
            }
        }
        
        public static string hestiaEmail {
            get {
                return ResourceManager.GetString("hestiaEmail", resourceCulture);
            }
        }
    }
}
