//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hestia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hestia.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activators/.
        /// </summary>
        public static string activatorsPath {
            get {
                return ResourceManager.GetString("activatorsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Add device.
        /// </summary>
        public static string addDeviceTitle {
            get {
                return ResourceManager.GetString("addDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hestia.
        /// </summary>
        public static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete!.
        /// </summary>
        public static string autocomplete {
            get {
                return ResourceManager.GetString("autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change credentials.
        /// </summary>
        public static string changeCredsTitle {
            get {
                return ResourceManager.GetString("changeCredsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change IP.
        /// </summary>
        public static string changeIpTitle {
            get {
                return ResourceManager.GetString("changeIpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string changeNameTitle {
            get {
                return ResourceManager.GetString("changeNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices/.
        /// </summary>
        public static string devicePath {
            get {
                return ResourceManager.GetString("devicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find server.
        /// </summary>
        public static string findServerTitle {
            get {
                return ResourceManager.GetString("findServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string hashCodeMultiplier {
            get {
                return ResourceManager.GetString("hashCodeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESTIA.IP.
        /// </summary>
        public static string hestiaIp {
            get {
                return ResourceManager.GetString("hestiaIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string initialCount {
            get {
                return ResourceManager.GetString("initialCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP_OF_SERVER.
        /// </summary>
        public static string ipOfServer {
            get {
                return ResourceManager.GetString("ipOfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        public static string pluginPathFront {
            get {
                return ResourceManager.GetString("pluginPathFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins/.
        /// </summary>
        public static string pluginsPath {
            get {
                return ResourceManager.GetString("pluginsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        public static string pluginsPathMid {
            get {
                return ResourceManager.GetString("pluginsPathMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Found:.
        /// </summary>
        public static string serverFound {
            get {
                return ResourceManager.GetString("serverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server.
        /// </summary>
        public static string serverNotFound {
            get {
                return ResourceManager.GetString("serverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HestiaClient.
        /// </summary>
        public static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _hestia._tcp..
        /// </summary>
        public static string serviceType {
            get {
                return ResourceManager.GetString("serviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ip here.
        /// </summary>
        public static string setIpHint {
            get {
                return ResourceManager.GetString("setIpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string toggleRank {
            get {
                return ResourceManager.GetString("toggleRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android version too low.
        /// </summary>
        public static string versionTooLow {
            get {
                return ResourceManager.GetString("versionTooLow", resourceCulture);
            }
        }
    }
}
