//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hestia.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Hestia.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string activatorCell {
            get {
                return ResourceManager.GetString("activatorCell", resourceCulture);
            }
        }
        
        public static string activatorsPath {
            get {
                return ResourceManager.GetString("activatorsPath", resourceCulture);
            }
        }
        
        public static string addDeviceChooseServerCell {
            get {
                return ResourceManager.GetString("addDeviceChooseServerCell", resourceCulture);
            }
        }
        
        public static string addDeviceTitle {
            get {
                return ResourceManager.GetString("addDeviceTitle", resourceCulture);
            }
        }
        
        public static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        public static string autocomplete {
            get {
                return ResourceManager.GetString("autocomplete", resourceCulture);
            }
        }
        
        public static string changeCredsTitle {
            get {
                return ResourceManager.GetString("changeCredsTitle", resourceCulture);
            }
        }
        
        public static string changeIpTitle {
            get {
                return ResourceManager.GetString("changeIpTitle", resourceCulture);
            }
        }
        
        public static string changeNameTitle {
            get {
                return ResourceManager.GetString("changeNameTitle", resourceCulture);
            }
        }
        
        public static string defaultNumberOfSections {
            get {
                return ResourceManager.GetString("defaultNumberOfSections", resourceCulture);
            }
        }
        
        public static string defaultNumberOfServers {
            get {
                return ResourceManager.GetString("defaultNumberOfServers", resourceCulture);
            }
        }
        
        public static string defaultPort {
            get {
                return ResourceManager.GetString("defaultPort", resourceCulture);
            }
        }
        
        public static string defaultsIpHestia {
            get {
                return ResourceManager.GetString("defaultsIpHestia", resourceCulture);
            }
        }
        
        public static string defaultsPasswordHestia {
            get {
                return ResourceManager.GetString("defaultsPasswordHestia", resourceCulture);
            }
        }
        
        public static string defaultsPortHestia {
            get {
                return ResourceManager.GetString("defaultsPortHestia", resourceCulture);
            }
        }
        
        public static string defaultsServerNameHestia {
            get {
                return ResourceManager.GetString("defaultsServerNameHestia", resourceCulture);
            }
        }
        
        public static string defaultsUsernameHestia {
            get {
                return ResourceManager.GetString("defaultsUsernameHestia", resourceCulture);
            }
        }
        
        public static string devicePath {
            get {
                return ResourceManager.GetString("devicePath", resourceCulture);
            }
        }
        
        public static string devicesMainCell {
            get {
                return ResourceManager.GetString("devicesMainCell", resourceCulture);
            }
        }
        
        public static string deviceTypeCell {
            get {
                return ResourceManager.GetString("deviceTypeCell", resourceCulture);
            }
        }
        
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        public static string findServerTitle {
            get {
                return ResourceManager.GetString("findServerTitle", resourceCulture);
            }
        }
        
        public static string hashCodeMultiplier {
            get {
                return ResourceManager.GetString("hashCodeMultiplier", resourceCulture);
            }
        }
        
        public static string hestiaIp {
            get {
                return ResourceManager.GetString("hestiaIp", resourceCulture);
            }
        }
        
        public static string initialCount {
            get {
                return ResourceManager.GetString("initialCount", resourceCulture);
            }
        }
        
        public static string ipDaan {
            get {
                return ResourceManager.GetString("ipDaan", resourceCulture);
            }
        }
        
        public static string ipOfServer {
            get {
                return ResourceManager.GetString("ipOfServer", resourceCulture);
            }
        }
        
        public static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        public static string loginToConnectSegue {
            get {
                return ResourceManager.GetString("loginToConnectSegue", resourceCulture);
            }
        }
        
        public static string manufacturerCell {
            get {
                return ResourceManager.GetString("manufacturerCell", resourceCulture);
            }
        }
        
        public static string newDeviceName {
            get {
                return ResourceManager.GetString("newDeviceName", resourceCulture);
            }
        }
        
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        public static string pluginPathFront {
            get {
                return ResourceManager.GetString("pluginPathFront", resourceCulture);
            }
        }
        
        public static string pluginsPath {
            get {
                return ResourceManager.GetString("pluginsPath", resourceCulture);
            }
        }
        
        public static string pluginsPathMid {
            get {
                return ResourceManager.GetString("pluginsPathMid", resourceCulture);
            }
        }
        
        public static string propertyCell {
            get {
                return ResourceManager.GetString("propertyCell", resourceCulture);
            }
        }
        
        public static string requestTimeout {
            get {
                return ResourceManager.GetString("requestTimeout", resourceCulture);
            }
        }
        
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        public static string serverCell {
            get {
                return ResourceManager.GetString("serverCell", resourceCulture);
            }
        }
        
        public static string serverConnectToDevicesSegue {
            get {
                return ResourceManager.GetString("serverConnectToDevicesSegue", resourceCulture);
            }
        }
        
        public static string serverFound {
            get {
                return ResourceManager.GetString("serverFound", resourceCulture);
            }
        }
        
        public static string serverNotFound {
            get {
                return ResourceManager.GetString("serverNotFound", resourceCulture);
            }
        }
        
        public static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        public static string serviceType {
            get {
                return ResourceManager.GetString("serviceType", resourceCulture);
            }
        }
        
        public static string setIpHint {
            get {
                return ResourceManager.GetString("setIpHint", resourceCulture);
            }
        }
        
        public static string toggleRank {
            get {
                return ResourceManager.GetString("toggleRank", resourceCulture);
            }
        }
        
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        public static string versionTooLow {
            get {
                return ResourceManager.GetString("versionTooLow", resourceCulture);
            }
        }
        
        public static string defaultsLocalHestia {
            get {
                return ResourceManager.GetString("defaultsLocalHestia", resourceCulture);
            }
        }
        
        public static string mainToAuth0 {
            get {
                return ResourceManager.GetString("mainToAuth0", resourceCulture);
            }
        }
        
        public static string mainToDevicesMain {
            get {
                return ResourceManager.GetString("mainToDevicesMain", resourceCulture);
            }
        }
        
        public static string mainToServerConnect {
            get {
                return ResourceManager.GetString("mainToServerConnect", resourceCulture);
            }
        }
        
        public static string auth0ViewController {
            get {
                return ResourceManager.GetString("auth0ViewController", resourceCulture);
            }
        }
        
        public static string defaultsAccessTokenHestia {
            get {
                return ResourceManager.GetString("defaultsAccessTokenHestia", resourceCulture);
            }
        }
        
        public static string devices2StoryBoard {
            get {
                return ResourceManager.GetString("devices2StoryBoard", resourceCulture);
            }
        }
        
        public static string mainStoryBoard {
            get {
                return ResourceManager.GetString("mainStoryBoard", resourceCulture);
            }
        }
        
        public static string navigationControllerDevicesMain {
            get {
                return ResourceManager.GetString("navigationControllerDevicesMain", resourceCulture);
            }
        }
        
        public static string apiURL {
            get {
                return ResourceManager.GetString("apiURL", resourceCulture);
            }
        }
        
        public static string clientId {
            get {
                return ResourceManager.GetString("clientId", resourceCulture);
            }
        }
        
        public static string domainAuth0 {
            get {
                return ResourceManager.GetString("domainAuth0", resourceCulture);
            }
        }
        
        public static string requestPath {
            get {
                return ResourceManager.GetString("requestPath", resourceCulture);
            }
        }
        
        public static string serversPath {
            get {
                return ResourceManager.GetString("serversPath", resourceCulture);
            }
        }
        
        public static string usersPath {
            get {
                return ResourceManager.GetString("usersPath", resourceCulture);
            }
        }
        
        public static string hestiaWebServerAddress {
            get {
                return ResourceManager.GetString("hestiaWebServerAddress", resourceCulture);
            }
        }
        
        public static string segueToServerDiscovery {
            get {
                return ResourceManager.GetString("segueToServerDiscovery", resourceCulture);
            }
        }
        
        public static string localGlobalViewController {
            get {
                return ResourceManager.GetString("localGlobalViewController", resourceCulture);
            }
        }
        
        public static string segueToLocalGlobalToServerSelect {
            get {
                return ResourceManager.GetString("segueToLocalGlobalToServerSelect", resourceCulture);
            }
        }
        
        public static string selectServerTitle {
            get {
                return ResourceManager.GetString("selectServerTitle", resourceCulture);
            }
        }
        
        public static string addDeviceIcon {
            get {
                return ResourceManager.GetString("addDeviceIcon", resourceCulture);
            }
        }
        
        public static string voiceControlIcon {
            get {
                return ResourceManager.GetString("voiceControlIcon", resourceCulture);
            }
        }
        
        public static string LocalSettingsScreen {
            get {
                return ResourceManager.GetString("LocalSettingsScreen", resourceCulture);
            }
        }
        
        public static string GlobalSettingsScreen {
            get {
                return ResourceManager.GetString("GlobalSettingsScreen", resourceCulture);
            }
        }
        
        public static string AddDeviceChooseServerViewController {
            get {
                return ResourceManager.GetString("AddDeviceChooseServerViewController", resourceCulture);
            }
        }
        
        public static string AddManufacturerViewController {
            get {
                return ResourceManager.GetString("AddManufacturerViewController", resourceCulture);
            }
        }
        
        public static string speechAccessDenied {
            get {
                return ResourceManager.GetString("speechAccessDenied", resourceCulture);
            }
        }
        
        public static string speechAllowAccess {
            get {
                return ResourceManager.GetString("speechAllowAccess", resourceCulture);
            }
        }
        
        public static string speechNotACommand {
            get {
                return ResourceManager.GetString("speechNotACommand", resourceCulture);
            }
        }
        
        public static string speechRecordError {
            get {
                return ResourceManager.GetString("speechRecordError", resourceCulture);
            }
        }
        
        public static string speechStartRecordProblem {
            get {
                return ResourceManager.GetString("speechStartRecordProblem", resourceCulture);
            }
        }
        
        public static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        public static string defaultPrefix {
            get {
                return ResourceManager.GetString("defaultPrefix", resourceCulture);
            }
        }
        
        public static string voiceControlIconInverted {
            get {
                return ResourceManager.GetString("voiceControlIconInverted", resourceCulture);
            }
        }
        
        public static string noDeviceFound {
            get {
                return ResourceManager.GetString("noDeviceFound", resourceCulture);
            }
        }
        
        public static string pronounceDeviceNameCorrectly {
            get {
                return ResourceManager.GetString("pronounceDeviceNameCorrectly", resourceCulture);
            }
        }
        
        public static string viewControllerAddDeviceProperties {
            get {
                return ResourceManager.GetString("viewControllerAddDeviceProperties", resourceCulture);
            }
        }
        
        public static string viewControllerAddDevice {
            get {
                return ResourceManager.GetString("viewControllerAddDevice", resourceCulture);
            }
        }
        
        public static string hestiaEmail {
            get {
                return ResourceManager.GetString("hestiaEmail", resourceCulture);
            }
        }
    }
}
